### PR TITLE
Use redis atomic operation when the cache backend is redis

### PR DESCRIPTION
**Pull request by mancausoft**
Using an atomic method to add the to the cache when redis is used

https://niwinz.github.io/django-redis/latest/#_redis_native_commands

### CODE REVIEW

**Comment by simon-weber** [comment]
👍 from me: anything else needed to merge this?

**Comment by jsocol** [comment]
Sorry, I've been slow to look at Python stuff lately.

I'm not sure why we need to add cache-backend-specific code at all. The django cache API makes it clear what should happen when [`.add()` is called](https://docs.djangoproject.com/en/2.2/topics/cache/#django.core.caches.cache.add):

> To add a key only if it doesn’t already exist, use the `add()` method. It takes the same parameters as `set()`, but it will not attempt to update the cache if the key specified is already present:

Does `django-redis` not implement that correctly? It seems like it is using the [`nx=True` parameter](https://github.com/niwinz/django-redis/blob/master/django_redis/client/default.py#L190) in its own client call.

**Comment by simon-weber** [comment]
Whoops; you're right. I hadn't bothered to check once I saw someone opened the PR.

**Comment by jsocol** [comment]
Thanks for the PR @mancausoft! I'm closing it out since it seems like this is already implemented in the Redis client, but if there's a way to demonstrate the problem, definitely feel free to reopen with repro code or a test that fails without this patch

**Pull request closed without merging**
