### PR TITLE
Add support for Django REST Framework's Request.data

### PR DESCRIPTION
**Pull request by ronanboiteau**
Support rate limiting on the key `data` for use with Django REST Framework's [`Request.data`](https://www.django-rest-framework.org/api-guide/requests/#data)

### CODE REVIEW

**Comment by muhammedattif** [comment]
I think we need this change as soon as possible, because most of developers use this package with `DRF` @jsocol

**Comment by Tom5421** [comment]
Hey, do we have an ETA on when this will be available?

**Comment by Tom5421** [comment]
Hey @muhammedattif @ronanboiteau would either of you like to fork this repo and add this feature?

It looks like the owner has no intention to merge any of these requests.

I would do it myself, but I am not that confident with Git.

**Comment by ronanboiteau** [comment]
**UPDATE:** Fork published to PyPi: [djangorestframework-ratelimit](https://pypi.org/project/djangorestframework-ratelimit/)

Original comment:

---

> Hey @muhammedattif @ronanboiteau would either of you like to fork this repo and add this feature?
> 
> It looks like the owner has no intention to merge any of these requests.
> 
> I would do it myself, but I am not that confident with Git.

Hey @Tom5421!

As a temporary solution you could use the branch [`v4.1.0-with-drf-support`](https://github.com/guestready/django-ratelimit/tree/v4.1.0-with-drf-support) on @guestready's fork. It's basically the changes from this pull request on a branch with no other commits beyond the tag [`v4.1.0`](https://github.com/jsocol/django-ratelimit/tree/v4.1.0). From our `requirements.txt`:

```txt
git+https://github.com/guestready/django-ratelimit.git@v4.1.0-with-drf-support#egg=django-ratelimit
```

As a more permanent solution we could publish the fork to PyPi as something like `djangorestframework-ratelimit`, if @jsocol doesn't think we should merge this into the original package.

**Comment by Tom5421** [comment]
Thanks for that @ronanboiteau.

I agree, a more permeant solution would be great.

**Comment by ronanboiteau** [comment]
Hey @Tom5421 @muhammedattif! 

I created the fork [djangorestframework-ratelimit](https://github.com/ronanboiteau/djangorestframework-ratelimit) and published [v1.0.0](https://github.com/ronanboiteau/djangorestframework-ratelimit/releases/tag/v1.0.0) to PyPi: https://pypi.org/project/djangorestframework-ratelimit/

It's based on django-ratelimit [v4.1.0](https://github.com/jsocol/django-ratelimit/releases/tag/v4.1.0) and it contains the changes suggested in this pull request + the changes from https://github.com/jsocol/django-ratelimit/pull/301 + various changes related to the package management / documentation. You can check the exact diff [here](https://github.com/jsocol/django-ratelimit/compare/v4.1.0...ronanboiteau:djangorestframework-ratelimit:v1.0.0).

**Comment by Tom5421** [comment]
Perfect, thank you for doing this!

**Comment by ronanboiteau** [comment]
Moved to fork [djangorestframework-ratelimit](https://github.com/ronanboiteau/djangorestframework-ratelimit)

Can be installed from PyPi: https://pypi.org/project/djangorestframework-ratelimit/

**Comment by DmytroLitvinov** [comment]
Maybe we can add support in the package like checking if `djangorestframework` is installed, then we add support for `data`?

**Pull request closed without merging**
