### PR TITLE
Cache increment delta value

### PR DESCRIPTION
**Pull request by kandziu**
I need change default value for increment in help function.

### CODE REVIEW

**Comment by jsocol** [comment]
Hi @vasilishin, thanks for the idea!

Can you add a little more info to the PR description? What's the use case for this? Especially what's the use case for adding it to the read-only `get_usage_count()` method? How should this be documented?

**Comment by vasilishin** [comment]
Hi @jsocol! I used **delta** like unique request weight and i added tests and documentation for this changes.

**Comment by jsocol** [comment]
Let me paraphrase and tell me if this is correct:

You want users to have some budget for the number of calls they can make, but certain calls cost more budget than others. So, for example, a user has 100 "credits" per hour, but calls to `/api/cheap` cost 1, and calls to `/api/expensive` cost 2. So they could make 100 calls to `/api/cheap`, or 50 to `/api/cheap` and 25 to `/api/expensive`.

Is that a reasonable description of what you're trying to do with ratelimit?

**Comment by vasilishin** [comment]
No, i have `/api/some` and for user1 is coast 1, for user2 is coast 2 and for user3 is 5...

**Comment by jsocol** [comment]
Ah, I see, ok! That's a very different situation and I think is better handled by using [callable rates](https://django-ratelimit.readthedocs.io/en/latest/rates.html#callables).

The idea is that you set the rate to a callable, say a function `get_api_rate`, which gets both the "group" of the ratelimit and the request object. Then you can check the user and somehow look up what their limit should be, e.g.:

```py
def get_api_rate(group, request):
    max_for_user = get_max_for_user(request.user)
    return (max_for_user, 3600)  # for a rate per hour

# ... snip

@ratelimit(rate=get_api_rate)
def my_api_method(request):
    # do your thing
    pass
```

does that make sense?

This gives you a lot more flexibility, too. Specifying the user cost would limit you to a number of ratios (e.g. if the limit is 100, a user can make 100, or 50, or 33, or 25 calls, but never 75 or 66). But specifying a per-user rate lets you use any numbers now or in the future.

There's an open ticket (#123) to document an example of how to do this.

**Comment by jsocol** [comment]
That said, I do think the cost-per-call use case is an interesting one! I would want to refine the implementation here a little bit but I think it may be worth doing.

**Comment by vasilishin** [comment]
All users have limit 3600 but all user requests must incremented his limit to different value. For example:
```python
cats = Cat.objects.filter(name__startswith="Tom")
ratelimited = is_ratelimited(
    request,
    key="user_or_ip",
    group="cats",
    rate="3600/h",
    increment=True,
    delta=cats.count()
)
if ratelimited:
    pass
else:
    ...
```

**Comment by jsocol** [comment]
The way to do this right now is definitely by using per-user limits by making `rate` callable, you just have to do the math to switch from "cost" to "limit". For example:

```python
from __future__ import division

def get_cat_rate(group, request):
    cats = Cat.objects.filter(name__startswith="Tom").count()
    limit = 3600 // cats
    return (limit, 3600) # 3600 seconds = 1 hour

@ratelimit(key='user_or_ip', rate=get_cat_rate)
def myview(request):
    pass
```

**Comment by vasilishin** [comment]
How i can solve this case? https://github.com/jsocol/django-ratelimit/pull/132/files#diff-3ad1065cf182cf933233f7adcd4d3ca1R440

**Comment by vasilishin** [comment]
My solution:
```python
    def send_mail(self, request):
        shared_to = self.cleaned_data["send_to"]
        rate_limit = settings.SHARED_FAVORITES_RATE_LIMIT
        shared_to = shared_to[:rate_limit]
        ratelimited = is_ratelimited(
            request,
            key="user_or_ip",
            group="shared_favorites",
            rate="{}/d".format(rate_limit),
            increment=True,
            delta=len(shared_to)
        )
        if ratelimited:
```

**Comment by jsocol** [comment]
Aha, so that's definitely a slightly different example, where you really do want a "credits" model. Like I said, I think that's interesting to pursue but I'd want to think more about the implementation, API design, and how it's documented. It's a fairly significant new feature.

**Comment by vasilishin** [comment]
For example how i can use is_ratelimited function now:
```python
def send_mail(self, request):
    shared_to = self.cleaned_data["send_to"]
    rate_limit = settings.SHARED_FAVORITES_RATE_LIMIT
    shared_to = shared_to[:rate_limit]
    # check request rate limit
    ratelimited = is_ratelimited(
        request,
        key="user_or_ip",
        group="shared_favorites",
        rate="{}/d".format(rate_limit),
        delta=len(shared_to)
    )
    if ratelimited:
        # request is limited
        raise Ratelimited
    else:
        # request is not limited
        # increase the rate count
        is_ratelimited(
            request,
            key="user_or_ip",
            group="shared_favorites",
            rate="{}/d".format(rate_limit),
            increment=True,
            delta=len(shared_to)
        )
        ...
```

**Comment by jsocol** [comment]
The error state definitely raises some interesting questions. With a typical ratelimit, it's possible to use the standard `Retry-After` header to communicate to clients that they need to back off and for how long. In this case, trying a request with a cost of 15 may fail, but a cost of 12 might not. And a request with a cost of 200 may _never_ be OK, but maybe 150 would be OK in 55 minutes.

**Comment by vasilishin** [comment]
We can do it as Twitter rate limiting headers https://developer.twitter.com/en/docs/basics/rate-limiting

**Comment by vasilishin** [comment]
Hi @jsocol. Friendly ping, what do you think about this pull request? I think it not change package API and could be used only as low level helper.

**Pull request closed without merging**
