### PR TITLE
Fix #58: Pass group to callable key.

### LINKED ISSUE #58: key callable only takes one argument but docs say two
Actually it looks like a callable passed in is only passed the request, but a dotted string which results in a callable is passed the group also. I thought the docs were wrong, but maybe it's the fact that a callable is only being passed a single argument. Perhaps for backward compatibility you can accept an alternate second param and shuffle if it remains `None`.

I should have a PR shortly with a recommendation.

### PR DESCRIPTION
**Pull request by pmclanahan**
This should do it I think.

### CODE REVIEW

**Comment by pmclanahan** [comment]
Huh. Thought I ran tests successfully. I'll fix that.

**Comment by pmclanahan** [comment]
Not sure about the docs update, but it's something :)

**Comment by jsocol** [comment]
LGTM, thanks pmac!

**Comment by pmclanahan** [comment]
My pleasure. This lib is helping me a whole lot with basket. Thank you!

**Pull request merged**
