### PR TITLE
Django 1.10 Middleware

### LINKED ISSUE #109: Django 1.10 Middleware Compatibility
The ratelimit middleware isn't compatible with Django 1.10's new middleware style

### PR DESCRIPTION
**Pull request by louis-haddrell**
Resolves #109 by making the middleware subclass from the Django deprecation MiddlewareMixin

https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware

### CODE REVIEW

**Comment by jsocol** [comment]
Thanks! This will break all Django <1.10, though, and 1.8 and 1.9 are still supported. Something like https://github.com/jsocol/django-waffle/pull/223/files will support both pre- and post-1.10

**Comment by louis-haddrell** [comment]
Good point. I've pushed another commit replicating your other code :)

**Comment by jsocol** [comment]
Awesome, thank you!

**Comment by jsocol** [comment]
Also, hmm, concerning that the tests didn't fail. Will look at that.

**Comment by adamchainz** [comment]
Would like to see this released on PyPI 😄

**Comment by jsocol** [comment]
@adamchainz any chance you want to help with things like that? Happy to add you to github/PyPI maintainers if you let me know your username

**Comment by adamchainz** [comment]
Yes I'm very happy to. Github username: adamchainz ( 😛 ), PyPI username: adamchainz

**Comment by jsocol** [comment]
@adamchainz You have access!

**Comment by adamchainz** [comment]
Thanks, released on PyPI at 1.0.1: https://pypi.python.org/pypi/django-ratelimit

**Pull request merged**
