### PR TITLE
Django 2.0 compatibility on request.user.is_authenticated

### PR DESCRIPTION
**Pull request by danmoz**
This fixes a Django 2.0 compatibility bug (#134)

### CODE REVIEW

**Comment by jsocol** [comment]
Hmm, clearly we don't have test coverage of this, but this will break on Django 1.8 which is still an LTS. I'm tentatively OK with that but we definitely need to note it.

**Comment by danmoz** [comment]
@adamchainz I've updated ``CHANGELOG``, thanks.

@jsocol Sorry I'm not sure I understand -- this branch should maintain Django 1.8 compatibility. I did take the liberty of changing the documentation examples to use the ``is_authenticated`` attribute instead of the method, but I feel that makes sense considering the method is officially deprecated in the latest version.

> clearly we don't have test coverage of this

Agreed, the bug didn't break any tests because MockUser does not behave like the real thing when it comes to ``is_authenticated``. Perhaps instantiating a User object in the tests in conjunction with ``Client`` and ``force_login()`` would be a better solution, however that seemed like a bit of a radical change.

**Comment by jsocol** [comment]
> Sorry I'm not sure I understand -- this branch should maintain Django 1.8 compatibility. I did take the liberty of changing the documentation examples to use the is_authenticated attribute instead of the method, but I feel that makes sense considering the method is officially deprecated in the latest version.

Shoot, I got confused with the example docs, my bad!

**Comment by jsocol** [comment]
Thank you! Sorry I lost track of this one for a little while

**Pull request merged**
