### PR TITLE
Fix for cache keys being evicted between add and incr/get on memcached

### PR DESCRIPTION
**Pull request by adamchainz**
Similar to #78 but with tests, see explanation on #78

### CODE REVIEW

**Comment by jsocol** [comment]
Was this covered in the fix in #88?

**Comment by adamchainz** [comment]
Yes, though it doesn't try as hard as this code to keep the count, I guess it makes sense in the face of connection errors.

**Comment by jsocol** [comment]
I'd happily accept a PR that swapped out those `0`s with the correct `initial_value`s, like this did.

**Comment by adamchainz** [comment]
I don't think that makes that much of a difference since evictions/connection errors should be rare in any deployment.

**Pull request closed without merging**
