### PR TITLE
Simplify tox.ini to generate all environments

### PR DESCRIPTION
**Pull request by adamchainz**
Simplify the tox.ini using the new features as documented under http://tox.readthedocs.org/en/latest/config.html#complex-factor-conditions .

Test:

Extracting and sorting the testenv headers from before, and adding space, you
get the following 19 lines:

```
[testenv:py26-1.4]
[testenv:py26-1.5]
[testenv:py26-1.6]

[testenv:py27-1.4]
[testenv:py27-1.5]
[testenv:py27-1.6]
[testenv:py27-1.7]
[testenv:py27-1.8]

[testenv:py33-1.5]
[testenv:py33-1.6]
[testenv:py33-1.7]
[testenv:py33-1.8]

[testenv:py34-1.5]
[testenv:py34-1.6]
[testenv:py34-1.7]
[testenv:py34-1.8]
```

Now `tox -l` outputs, with spaces added, the following 19 lines, which I
checked to correspond to the above:

```
py26-django14
py26-django15
py26-django16

py27-django14
py27-django15
py27-django16
py27-django17
py27-django18

py33-django15
py33-django16
py33-django17
py33-django18

py34-django15
py34-django16
py34-django17
py34-django18
```

Also the tests pass.

### CODE REVIEW

**Comment by jsocol** [comment]
Like my comment on #93, would you mind dropping 1.5 and 1.6? (1.4 is the last ESR so is still supported for a little while.)

**Comment by adamchainz** [comment]
Done!

**Comment by adamchainz** [comment]
Actually on the "Supported Versions" grid, 1.4 is unsupported since the start of the month: https://www.djangoproject.com/download/#supported-versions

```
Drop support for it too?
y/n >
```

**Comment by jsocol** [comment]
Hallelujah, I guess it has been >6 months since 1.8 came out!

```
Drop support for it too?
y/n > melt wizard
I don't understand.
Drop support for it too?
y/n > y
```

**Comment by adamchainz** [comment]
scared wizard

**Comment by jsocol** [comment]
Thanks!

**Pull request merged**
